### PR TITLE
Fix/federation union type

### PR DESCRIPTION
**Pull request by spetrunin**
original PR:
https://github.com/jensneuse/graphql-go-tools/pull/283

Issue:
https://github.com/jensneuse/graphql-go-tools/issues/276

### CODE REVIEW

**Comment by chedom** [comment]
@spetrunin  I have added one more [commit](https://github.com/jensneuse/graphql-go-tools/pull/283/commits/aa10d4ca518cc19bc03d1a57009e554d98184192)

**Comment by jensneuse** [comment]
@chedom Are you able to cover both commits with a test in your PR on https://github.com/jensneuse/graphql-go-tools/pull/283?
As far as I can see, we're currently lacking end-to-end tests to fully validate that the union/interface issue is solved.
Additionally, it would be nice to have tests covering the null fields as well for both object and array.

**Comment by chedom** [comment]
> @chedom Are you able to cover both commits with a test in your PR on [jensneuse#283](https://github.com/jensneuse/graphql-go-tools/pull/283)?
> As far as I can see, we're currently lacking end-to-end tests to fully validate that the union/interface issue is solved.
Ok, I'll add.
> Additionally, it would be nice to have tests covering the null fields as well for both object and array.
Did you mean e2e tests or unit tests for `resolver` ?

**Comment by jensneuse** [comment]
> > @chedom Are you able to cover both commits with a test in your PR on [jensneuse#283](https://github.com/jensneuse/graphql-go-tools/pull/283)?
> > As far as I can see, we're currently lacking end-to-end tests to fully validate that the union/interface issue is solved.
> 
> Ok, I'll add.
> 
> > Additionally, it would be nice to have tests covering the null fields as well for both object and array.
> 
> Did you mean e2e tests or unit tests for `resolver` ?

For the changes of the resolver (nullable fields), unit tests should be sufficient.

Additionally (but optional) it would be good to have e2e tests for federation including union & interface fix.
E.g. spin up 2 httptest servers with gqlgen, merge the APIs, then run a few test queries and validate the responses.
This would give us more confidence in the future to expand the federation implementation, e.g. it would make merging the batch feature easier because we can end to end test it.

**Comment by chedom** [comment]
@jensneuse  e2e tests for federation have been added.

> For the changes of the resolver (nullable fields), unit tests should be sufficient.

There were unit tests in my [PR](https://github.com/jensneuse/graphql-go-tools/pull/283)
There are plenty of tests for  nullable fields. They start [here](https://github.com/jensneuse/graphql-go-tools/blob/master/pkg/engine/resolve/resolve_test.go#L1065). 
Modified/added tests:
One [test](https://github.com/jensneuse/graphql-go-tools/pull/283/files#diff-6c742edcb85d42ca4ef4749c8a9db1eeb568a17e16e7b5314fe1e7b5559cfbdeR1152) has been slightly modified (cover case when Array path is not empty)  and one [more](https://github.com/jensneuse/graphql-go-tools/pull/283/files#diff-6c742edcb85d42ca4ef4749c8a9db1eeb568a17e16e7b5314fe1e7b5559cfbdeR521) has been added (cover issue  with  __typename  for Nullable field) .

**Pull request closed without merging**
